config/routes.rb
YoutubeReindex::Application.routes.draw do

  resources :videos, :only => [:index,:show]
  
  root :to => "videos#index"

end

app/models/geo_position.rb
class GeoPosition

  KMS_PER_MILE = 1.609
  EARTH_RADIUS_IN_MILES = 3963.19
  EARTH_RADIUS_IN_KMS = EARTH_RADIUS_IN_MILES * KMS_PER_MILE

  class << self
    def distance_between(from, to)
      from  = self.ll from
      to    = {:lat => to.split(',').first, :lng => to.split(',').last}
      return 23423423 unless from
      begin
        EARTH_RADIUS_IN_KMS * 
            Math.acos( Math.sin(deg2rad(from[:lat])) * Math.sin(deg2rad(to[:lat])) + 
            Math.cos(deg2rad(from[:lat])) * Math.cos(deg2rad(to[:lat])) * 
            Math.cos(deg2rad(to[:lng]) - deg2rad(from[:lng])))
      rescue Errno::EDOM
        0.0
      end
    end
  
    def ll(video)
      if video.send(:'georss:where') && video.send(:'georss:where')['gml:Point'] && video.send(:'georss:where')['gml:Point']['gml:pos']
        pos = video.send(:'georss:where')['gml:Point']['gml:pos'].split();
        {:lat => pos.first, :lng => pos.last}
      else
        nil
      end
    end
  
    def deg2rad(degrees)
      degrees.to_f / 180.0 * Math::PI
    end
  
  end
end

app/models/video_collection.rb
# encoding: utf-8

require 'ostruct'

module VideoCollection

  DISTANCE = 0
  DURATION = 1
  PUBLISHED = 2
  RATING = 3
  VIEWS = 4

  def self.new(hash, params = {})
    hash.extend(self)
    hash
  end
  
  def results_sorted(params)
    case params[:order_by]
    when VideoCollection::DISTANCE
      videos = results_by_distance(params[:location])
    when DURATION
      videos = results_by_duration
    when PUBLISHED
      videos = results_by_publication
    when RATING
      videos = results_by_rating
    when VIEWS
      videos = results_by_views
    else
      videos = results
    end
    videos
  end
  
  protected

  def key(key)
    self['feed'] && self['feed'][key]
  end

  def results
    results = [key("entry")].flatten.compact
    results.map do |result|
      alt_result = result.inject({}) do |hash, (k, v)|
        result[k.downcase] = v
        result
      end
      OpenStruct.new(alt_result)
    end
  end

  def results_by_distance(point)
    results.sort do |a,b|
      GeoPosition.distance_between(a, point) <=> GeoPosition.distance_between(b, point)
    end
  end

  def results_by_duration
    results.sort do |a,b|
      a.send(:'media:group')['yt:duration']['seconds'] <=> b.send(:'media:group')['yt:duration']['seconds']
    end
  end

  def results_by_publication
    results.sort do |a,b|
      # TODO: je toto spravne porovnanie 2 XSL dates?
      a.send(:'published') <=> b.send(:'published')
    end
  end
  
  def results_by_rating
    results.sort do |a,b|
      a.send(:'gd:rating')['average'] <=> b.send(:'gd:rating')['average']
    end
  end

  def results_by_views
    results.sort do |a,b|
      a.send(:'yt:statistics')['viewCount'] <=> b.send(:'yt:statistics')['viewCount']
    end
  end
end

app/models/video_search.rb
# encoding: utf-8

class VideoSearch

  include HTTParty
  
  format :xml
  
  class << self
    def new(params)
      params.merge!({:'max-results' => 10})
      hash = self.get('http://gdata.youtube.com/feeds/api/videos', :query => params)
      VideoCollection.new(hash)
    end
    
    def get_video(video_id)
      hash = self.get("http://gdata.youtube.com/feeds/api/videos/#{video_id}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/videos_controller.rb
# encoding: utf-8

class VideosController < ApplicationController
  require 'geokit'
  
  def index
    order = params[:o].to_i
    keyword = params[:q]
    location = params[:location]

    if location.blank?
      location = Geokit::Geocoders::IpGeocoder.geocode(request.remote_ip).city
    end

    geo_location = Geokit::Geocoders::GoogleGeocoder.geocode location.removeaccents
    params = {:q => keyword, :location => geo_location.ll, :order_by => order}

    @order_by_options = {
      'Distance' => VideoCollection::DISTANCE,
      'Duration' => VideoCollection::DURATION,
      'Published (Date)' => VideoCollection::PUBLISHED,
      'Rating' => VideoCollection::RATING,
      'Views' => VideoCollection::VIEWS}
    @videos = VideoSearch.new(params).results_sorted(params)
  end
  
  def show
    @video = VideoSearch.get_video(params[:id])['entry']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def video_id(video)
    video.id.split('/').pop
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{"http-equiv" => "Content-Type", :content => "text/html; charset=utf-8"}
    %title= yield(:title)
    = stylesheet_link_tag :all
    = javascript_include_tag 'jquery-1.4.2-min', 'rails'
    = yield :head
  %body
    #container
      %h1= link_to t('.headline'), "/"
      = render :partial => 'shared/flashes'
      #header
      #menu
        = yield :menu
      = yield

      = render :partial => 'shared/footer'

app/views/search/index.html.haml
- @videos.each do |video|
  = render :partial => 'video', :locals => {:video => video}

= content_for :menu do  
  = form_tag(search_index_path, :method => "get") do
    = label_tag(:q, "Search for:")
    = text_field_tag :q, params[:q], :class => 'text'
    = submit_tag "Search", :class => 'submit'

app/views/shared/_flashes.html.haml
- flash.each do |key, value|
  %div{:id => "flash_#{key}", :class => "flash-notice"}= value

app/views/shared/_footer.html.haml
#footer
  %span.copyright= t('.copyright')

app/views/videos/_video.html.haml
%dl.video
  %dt.title= link_to (truncate video.title, :length => 20), "/videos/#{video_id video}", :title => video.title
  %dd.img= link_to (image_tag video.send(:"media:group")['media:thumbnail'].first['url']), "/videos/#{video_id video}", :title => video.title

app/views/videos/index.html.haml
.videos
  - @videos.each do |video|
    = render :partial => 'video', :locals => {:video => video}

  = content_for :menu do
    = form_tag(videos_path, :method => "get") do
      = label_tag(:q, "Search for:")
      = text_field_tag :q, params[:q], :class => 'text'
      = label_tag(:location, "Location:")
      = text_field_tag :location, params[:location], :class => 'text'
      = label_tag(:order, "Order by:")
      = select_tag :o, options_for_select(@order_by_options, params[:o]), :class => 'select'
      = submit_tag "Search", :class => 'submit'

app/views/videos/show.html.haml
.videos
  %h2= @video['title']

  .author
    %span Autor:
    %span.name= @video['author']['name']

  %object{:width => "480", :height => "385"}
    %param{:name => "movie", :value => "http://www.youtube.com/v/#{params[:id]}?fs=1&amp;hl=en_US&amp;rel=0"}
    %param{:name => "allowFullScreen", :value => "true"}
    %param{:name => "allowscriptaccess", :value => "always"}
    %embed{:src => "http://www.youtube.com/v/#{params[:id]}?fs=1&amp;hl=en_US&amp;rel=0", :type => "application/x-shockwave-flash", :allowscriptaccess => "always", :allowfullscreen => "true", :width => "480", :height => "385"}